name: test-gpu

on:
  push:
    paths:
      - resnet-pytorch/**
      - tests/**

jobs:
  test-gpu-run:
    container:
      image: nvcr.io/nvidia/pytorch:20.03-py3
      options: --gpus all
    runs-on: [self-hosted, Linux, x64]
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        torch-version: [1.8.0]
        torchvision-version: [0.9.0]
        cuda-version: [10.2]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install pytorch==${{ matrix.torch-version }} torchvision==${{ matrix.torchvision-version }} cudatoolkit=${{ matrix.cuda-version }} -c pytorch
        pip install -r resnet-pytorch/requirements.txt
        pip install -r tests/requirements.txt
    
    - name: Run tests
      shell: bash -l {0}
      run: pytest tests/test_resnet_gpu.py